### ISSUE TITLE
Не могу запустить exe

### ISSUE THREAD

**Issue by enusr2k** [ze0nni/ProtoDock#4]
Установил все 
.NET Desktop Runtime
.NET Runtime
ASP.NET Core Runtime
версий 7, 6, 5, 3. Все равно не запускается. При запуске просит скачать, но при нажатии ОК ничего не происходит.

**Comment by ze0nni** [comment]
По идее нужен [netcore 3.](https://dotnet.microsoft.com/en-us/download/dotnet/3.1)

Попробую вечером еще раз пробежаться по зависимостям

**Comment by ze0nni** [comment]
Еще возможно не хватает [Net4.5](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net45)

**Comment by enusr2k** [comment]
Версия 1.5 запустилась! 
Извиняюсь, я похоже не тот .NET устанавливал, т.к. у меня нет папки C:\Program Files\dotnet\sdk. 
Получается, что нужен был SDK? 
Софт отличный! Только иконки трея бы поменьше, можен быть 16х16 и в 2 ряда?

**Comment by enusr2k** [comment]
![2022-12-14_194555](https://user-images.githubusercontent.com/115537081/207628084-05332ba1-2028-41cf-acca-eb820f0bb4fa.png)

Вот список того, что я установил.

**Comment by 29039** [comment]
choco install -y dotnetcore-desktopruntime
